### ISSUE TITLE
Analyzing data on more than one band in functions like take_noise_psd

### ISSUE THREAD

**Issue by hlym** [slaclab/pysmurf#112]
Currently on the princeton branch we can only take data on one band at a time.

**Comment by swh76** [comment]
Clarifying ; data is taken on all bands with configured channels.  I think the issue here is that functions like `take_noise_psd` ; 
https://github.com/slaclab/pysmurf/blob/b397b6d7382fff7794a367225ed80b6a319381f6/pysmurf/debug/smurf_noise.py#L11
take a band argument ; they only analyze data from the specified band, even though data from the other bands is in the saved data.

**Comment by swh76** [comment]
Related question for @jesusvasquez333 ; what's the status of streaming with more than 512 channels?

**Comment by eyyoung24** [comment]
see https://github.com/slaclab/pysmurf/commit/ab8d398360cb7b48f152e995ca0b565590b152e5
