### ISSUE TITLE
Errors during pysmurf setup

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#293]
I'm getting two errors when setting up pysmurf:
```
cannot connect to smurf_emulator:AMCc:FpgaTopLevel:AmcCarrierCore:AmcCarrierTiming:EvrV2CoreTriggers:EvrV2TriggerReg[0]:Enable
cannot connect to smurf_emulator:AMCc:FpgaTopLevel:AmcCarrierCore:AmcCarrierTiming:EvrV2CoreTriggers:EvrV2ChannelReg[0]:Enable
```

I'm not 100% sure but I remember seeing something like this on the princeton system also. Have these variables been removed from the rogue tree? I don't see where this is trying to be accessed. If it's being set somewhere in pysmurf can this be safely removed? Or is it something from the pysmurf.cfg file that I'm using?

**Comment by swh76** [comment]
Where are you seeing this?  This is due to an API change in rogue; for your rogue version the registers are likely now named 
smurf_emulator:AMCc:FpgaTopLevel:AmcCarrierCore:AmcCarrierTiming:EvrV2CoreTriggers:EvrV2TriggerReg[0]:EnableReg and smurf_emulator:AMCc:FpgaTopLevel:AmcCarrierCore:AmcCarrierTiming:EvrV2CoreTriggers:EvrV2ChannelReg[0]:EnableTrig.  However, this has been fixed in the master branch of pysmurf.  See here:
https://github.com/slaclab/pysmurf/blob/8f93205348d447033879377abf9d3d059a41a2fa/python/pysmurf/client/command/smurf_command.py#L3790
What branch are you using?

**Comment by swh76** [comment]
Resolved, see my comment.
