### ISSUE TITLE
Reliance of startup args in pysmurf functions

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#427]
Right now the pysmurf function `which_bays` depends on the smurf_startup arguments to see which bays have been disabled. I'm in the process of moving that sort of configuration for my streaming script into the sys_config file instead of doing everything with command line arguments, which will break this function in kind of a weird and unintuitive way. 

Is there any chance we can change this so that the enabled bays are themselves saved in a rogue variable and avoid using the startup_args in future smurf functions?

**Comment by jesusvasquez333** [comment]
@jlashner Please note that since version `v4.0.0` these arguments (`--disable-bayX`, and the default configuration files) are automatically generated by detecting the type of hardware (see: https://github.com/slaclab/pysmurf/pull/305 and https://github.com/slaclab/pysmurf/pull/285). So, I would advice that you use this autogeneration as well, instead of using configuration files.

See here as well:
https://github.com/slaclab/pysmurf/blob/master/docker/server/scripts/start_server.sh#L117-L126
and 
https://github.com/slaclab/pysmurf/blob/master/docker/server/scripts/server_common.sh#L345-L585

**Comment by jlashner** [comment]
great, as long as the startup_args aren't pulled from the argv on the command line that should be fine

**Comment by jlashner** [comment]
Looks like it's pulling from argv which won't work for me even if I'm calling your startup script.... https://github.com/slaclab/pysmurf/blob/670c9db09b71514835c72d2559d1617a4d11ef85/python/pysmurf/core/devices/_SmurfApplication.py#L53

This is because the way my function works is that it starts a python session, reads the sys_config file to get some configuration such as communication type and default file paths, calls your startup script and then extracts the new command line args from stdout to pass to pysmurf's argparser. The reason for doing this was so that I didn't have to hardcode our streaming script into the start_server.sh function, and so I could pull defaults from our own config files before passing to start_server. But this means that the modified arguments that I get from start_server.sh are not present in argv.

**Comment by swh76** [comment]
@jlashner see e.g.

https://github.com/slaclab/pysmurf/blob/fabc41fae8bf748fcd2812857b6f5d21dae0898c/docker/server/scripts/start_server.sh#L121

which constructs the args to the cmb_eth.py/cmb_pcie.py script.  Or are you directly running the cmb_eth.py/cmb_pcie.py scripts, and not calling start_server.sh?

**Comment by jlashner** [comment]
We need to run our own start script to put the streamer in, so I can't run any of those scripts, since `cmb_eth.py/cmb_pcie.py` are hardcoded in, and we want to pull arguments from sys_config instead of the command line. What we do is:
 - Run `stream.py`
 - `stream.py` runs `start_server.sh` with args pulled from our own config files (not command line arguments)
 - Receive back modified arguments (like `--disable-bay1`) to use in our script through stdout
 - Parse those arguments with our parser + the pysmurf-server parser to get the variables to pass to the rogue root.

The thing is that `which_bays` relies on the `argv` arguments passed to our start script, so the arguments that we receive from running `start_server.sh` are not included. Anyway I think relying on argv to get info about the smurf state is just not reliable unless we're running the server the exact same way you're running it, which is difficult.

**Comment by jesusvasquez333** [comment]
Hi Jack, please note that I moved all the main functions from our [start_server.sh](https://github.com/slaclab/pysmurf/blob/master/docker/server/scripts/start_server.sh) script to a common [server_common.sh](https://github.com/slaclab/pysmurf/blob/master/docker/server/scripts/server_common.sh) script so that you won't have to rely nor call out start_server.sh script. The ideas was that you could then source the common script from your custom script and still have the same functions we have, which is what I do [here](https://github.com/slaclab/pysmurf/blob/master/docker/server/scripts/start_server.sh#L8).
