### ISSUE TITLE
start_server.sh "no exec" mode

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#434]
## Describe the problem
Currently to run the smurf-streamer, we run a modified version of the start_server.sh script in a subprocess that runs all of the same `server_common` functions, but instead of running another python script when it finishes, it just returns the modified command line args through stdout instead of running another python file. 

It would be great if instead of using our own shell script, we could add a `--no-exec` option to the official one that just prints the command line arguments instead of starting a python script.

**Comment by jesusvasquez333** [comment]
I think a better solution is to move [these calls|https://github.com/slaclab/pysmurf/blob/master/docker/server/scripts/start_server.sh#L99-L126] in `start_server.sh` to a wrapper function defined in `server_common.sh`. This wrapper function will return the list or arguments. 

For example, I can define a function called `initialize` in `server_common.sh` which will look something like:
```bash
initialize()
{
    # The first argument points to a variable name to store the resulting argument list
    local __result_args=$1

    # List of arguments 
    local init_args=""

    # Validate the selected communication type
    validateCommType

    # Validate the selected slot number
    validateSlotNumber

    # Get FPGA IP address
    getFpgaIpAddr

    # Look for pyrogue files
    findPyrogueFiles

    # Firmware version checking
    checkFW

    # Do a hard boot, if requested
    hardBoot

    # Auto-detect hardware type
    ## Detect type of AMCs, and get specific server startup arguments
    ## for each specific type and add them to the list of arguments
    detect_amc_board amcs_args
    init_args +=" ${amcs_args}"

    ## Detect type of carrier, and get specific server startup arguments
    ## for each specific type and add them to the list of arguments
    detect_carrier_board carrier_args
    init_args +=" ${carrier_args}"

    # Write the result to the defined variable
    eval $__result_args="'${init_args}'"
}
```

Then the `start_server.sh` will look something like:
```bash
# Import function from common script
. server_common.sh

# Usage message
usage()
{
...
}

# Read inputs arguments
...

# Call the initialize functions
initialize init_args
args+=" ${init_args}"

# Call the appropriate server startup script depending on the communication type
if [ ${comm_type} == 'eth' ]; then
    echo "Staring the server using Ethernet communication..."
    cmd="/usr/local/src/pysmurf/server_scripts/cmb_eth.py  ${args}"
else
    echo "Staring the server using PCIe communication..."
    cmd="/usr/local/src/pysmurf/server_scripts/cmb_pcie.py ${args}"
```

In the future, is we add new functionality, those new calls will be added to `initialize` wrapper function, without changing the `start_server.sh` script. 

Then, from OCS you can just call the same `initialize` function defined in `server_common.sh`

**Comment by jlashner** [comment]
I agree, this also sounds like a good solution. One more thing is that the [argument parsing](https://github.com/slaclab/pysmurf/blob/83d07327cd3767b63c65cd05b06d8b3b8919d8f1/docker/server/scripts/start_server.sh#L56-L97) should also be moved to smurf_common. Since if you add a new function that checks a new command line arg, this will also need to be propagated to our startup script.

**Comment by jesusvasquez333** [comment]
@jlashner Yes, I think it make sense to move the argument parsing to the common script so that it can be reused if needed. However, in your particular case I though you were not using command line arguments, but instead setting them in a configuration file. If this is true, then you are not using this argument parsing code. Is that correct?
In the future, if we add new function (inside the `initialize` function, which requires some flags to be set, then you will need to add those to your config file.

**Comment by jlashner** [comment]
Hi Jesus, that is partly true. I am not passing any arguments to my python script, but when I call my `start_server.sh` as a subprocess I am passing the command line args that it needs to operate, so I still need the shell script's argument parser. I'll send you the diagram that I'm making when its finished and hopefully that'll clear things up.

**Comment by jesusvasquez333** [comment]
@jlashner I took a look a your diagram, and now I have a better idea of what you are trying to do. So I agree, I will move the [argument parsing code](https://github.com/slaclab/pysmurf/blob/83d07327cd3767b63c65cd05b06d8b3b8919d8f1/docker/server/scripts/start_server.sh#L56-L97) to a function defined in `server_common.sh`, called `arg_parser()`. I will move the `usage` function as well as it is related to this argument parsing.

So, the `start_server.sh` script will look something like this:
```bash
# Import function from common script
. server_common.sh

# Read inputs arguments
args=""
arg_parser args
# Call the initialize functions
initialize init_args
args+=" ${init_args}"

# Call the appropriate server startup script depending on the communication type
if [ ${comm_type} == 'eth' ]; then
    echo "Staring the server using Ethernet communication..."
    cmd="/usr/local/src/pysmurf/server_scripts/cmb_eth.py  ${args}"
else
    echo "Staring the server using PCIe communication..."
    cmd="/usr/local/src/pysmurf/server_scripts/cmb_pcie.py ${args}"
```

Then you can write your own start script, similar to this, but returning the lost of arguments at the end instead of calling our python startup scripts.
