### ISSUE TITLE
get/set flux_ramp_freq has different scaling values

### ISSUE THREAD

**Issue by eyyoung24** [slaclab/pysmurf#449]
## Describe the bug
Matt found an inconsistency in our flux_ramp_freq code

https://github.com/slaclab/pysmurf/blob/fabc41fae8bf748fcd2812857b6f5d21dae0898c/python/pysmurf/client/command/smurf_command.py#L3350 

https://github.com/slaclab/pysmurf/blob/fabc41fae8bf748fcd2812857b6f5d21dae0898c/python/pysmurf/client/command/smurf_command.py#L3340

See the hardcoded scaling values. These values should not be hard-coded into pysmurf.

**Comment by swh76** [comment]
RampMaxCnt is in the 307.2MHz clock domain in FW, so I suspect this should just be 3.072e5 (to report in kHz, not MHz).  Instead of hardcoding, could poll `digitizerFrequencyMHz` register via
https://github.com/slaclab/pysmurf/blob/fabc41fae8bf748fcd2812857b6f5d21dae0898c/python/pysmurf/client/command/smurf_command.py#L1803
which is 614.4MHz, and divide by 2.  @jmdewart says the relationship between the RampMaxCnt rate and the digitizer rate is that the default FW rate is 307.2MHz but you get x2 I and x2 Q samples per clock, which is why the digitizer rate is 614.4MHz (2x the default rate).

**Comment by mhasself** [comment]
There are also docstring issues in that vicinity... some units are stated to be in Hz but are clearly kHz.
