### ISSUE TITLE
get_tes_high_current_mode

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#610]
## Describe the problem
Right now it seems like there's no clear way to get whether or not a bias line is in high current mode. It seems like this is just stored as a bit in the cryo-card relay: https://github.com/slaclab/pysmurf/blob/5e231d4445e34095f5ab7728dccaa09978d83335/python/pysmurf/client/util/smurf_util.py#L3113-L3125

So it seems like it would be easy to have a function read this bit off and tell you if the biasline is in high-current mode. Is there any reason why this doesn't exist? We'd use it in a lot of sodetlib scripts, so if it's just a matter of implementing it I can do it and submit a PR, but I'm wondering if there's a deeper reason.

**Comment by cyndiayu** [comment]
@jlashner sort of. The cryocard you have doesn't have readback because the relays mechanically latch. You can read off the state by asking what bit was last set, but if the relay fails to flip for any reason, your reading would be a lie. Nominally we set everything to a known (low) state at startup, but we have seen in the past (rare) instances of relays failing to latch even though the bit was set. 

The new cryocards will have solid state relays so you can actually query the card directly and ask what state it's in.

**Comment by jlashner** [comment]
I see... I still think it would be useful to have a function that reads off the last bit set (like what I implemented in #611) but we'd have to make it clear either in the docstring, or by calling the function something clearer like `get_tes_bias_mode_commanded`. But if you're uncomfortable with having it in pysmurf, I can just put the temporarily function in sodetlib until we get the new cryocard.

**Comment by swh76** [comment]
@jlashner we're not planning to do any further work on this but can add your proposed function if you like.  But isn't there already a way to readback what the relays have been set to from the PIC?  Due to a technical issue the new cryocards will still be the mechanical relays we have on the C02 rev, so won't have state readback on the new cards, unfortunately.

**Comment by jlashner** [comment]
Yeah  we already merged the function in PR #611 so I think we can close this.

**Comment by swh76** [comment]
Great, thanks @jlashner.  Closing.
