### ISSUE TITLE
Main vs Develop Branches

### ISSUE THREAD

**Issue by kmharrington** [slaclab/pysmurf#671]
## Describe the bug
[This commit](https://github.com/slaclab/pysmurf/commit/e12b783a829129936840010d0cf8ee5a9defb95d) was sent to `main` instead of `develop` and that's breaking things farther down in SO testing. I tried switching to main but it seems like there's still differences between the two branches and I'm getting other errors. 

## Additional details
Could we apply that commit to both branches? As soon as possible?

**Comment by aer7** [comment]
Hi, Katie. Jack recently merged that commit into develop, so hopefully that fixes your issue. Because main and develop haven't been merged since about February, they have diverged significantly (see https://github.com/slaclab/pysmurf/compare/develop). I'll try and figure out a good solution to this problem.

Agustin
